// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkzcnrxkufnyiputshgv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJremNucnhrdWZueWlwdXRzaGd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxOTQ3MjksImV4cCI6MjA2Nzc3MDcyOX0.urpJ711gFwfeJ8P3_mK4c3xXXnhhjX5kNJrDw2hKa64";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});